name: Main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: nextjs
      # Use the commit SHA as a unique image tag.
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run tests
        run: npm test  # Or use a specific test script if you have it in package.json

      - name: Upload test results as an artifact (optional)
        if: failure()  # Only upload if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results/  # Path to your test result directory
