name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      source: ${{ steps.filter.outputs.source }}
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - uses: actions/checkout@v3
      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            source:
              - 'netflixclone/**'
              - '.github/workflows/**'
            terraform:
              - 'terraform/**'

  build:
    needs: filter
    runs-on: ubuntu-latest
    outputs:
      built: ${{ steps.build_image.outputs.built }}
    env:
      ECR_REPOSITORY: nextjs
      IMAGE_TAG: latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image if Source Changed
        id: build_image
        run: |
          if [ "${{ needs.filter.outputs.source }}" == "true" ]; then
            echo "Source changes detected. Building Docker image..."
            docker build -t $ECR_REPOSITORY:latest -f netflixclone/Dockerfile netflixclone
            docker tag $ECR_REPOSITORY:latest ${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
            docker push ${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=built::true"
          else
            echo "No source changes detected. Skipping build."
            echo "::set-output name=built::false"
          fi

  deploy:
    needs: [filter, build]
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: nextjs
      IMAGE_TAG: latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6

      - name: Terraform Init, Plan, and Apply
        working-directory: terraform/netflixclone
        run: |
          terraform init \
            -backend-config="bucket=the-community-a-coding-cohort-tf-state-bucket" \
            -backend-config="key=nextjs/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-locks" \
            -backend-config="encrypt=true"
          terraform plan \
            -var="hosted_zone_id=${{ secrets.HOSTED_ZONE_ID }}" \
            -var="ecr_repository_url=${{ secrets.ECR_REPOSITORY_URL }}" \
            -out=tfplan
          terraform apply -auto-approve tfplan