name: Bootstrap Remote State

on:
  workflow_dispatch:  # For manual triggering

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6

      - name: Terraform Init (Remote State)
        working-directory: terraform/remote_state
        run: terraform init

      - name: Terraform Plan (Remote State)
        working-directory: terraform/remote_state
        run: terraform plan

      - name: Terraform Apply (Remote State)
        working-directory: terraform/remote_state
        run: terraform apply -auto-approve